import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TopNav from "@/components/Navbar/TopNav";
import Sidebar from "@/components/Sidebar/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex min-h-screen">
          {/* Sidebar */}
          <div className="w-64  min-h-screen">
            <Sidebar />
          </div>

          {/* Main area */}
          <div className="flex-1 flex flex-col">
            {/* Top Navbar */}
            <div>
              <TopNav />
            </div>

            {/* Scrollable main content */}
            <div className="flex-1  min-h-screen  overflow-y-scroll bg-gray-50 p-4">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
