import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TopNav from "@/components/Navbar/TopNav";
import Sidebar from "@/components/Sidebar/Sidebar";
import { AppProvider } from "@/components/ContexProvider/ContexProvider";
import ANotherbar from "@/components/Sidebar/AnotherBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppProvider>
          <div className="flex ">
            {/* Sidebar */}
            <div className="">
              <Sidebar />
              {/* <ANotherbar /> */}
            </div>

            {/* Main area */}
            <div className="">
              {/* Top Navbar */}
              <div>
                <TopNav />
              </div>

              {/* Scrollable main content */}
              <div className="  min-h-screen  overflow-y-scroll bg-gray-50 p-4">
                {children}
              </div>
            </div>
          </div>
        </AppProvider>
      </body>
    </html>
  );
}
