import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TopNav from "@/components/Navbar/TopNav";
import Sidebar from "@/components/Sidebar/Sidebar";
import { AppProvider } from "@/components/ContexProvider/ContexProvider";
import ANotherbar from "@/components/Sidebar/AnotherBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppProvider>
          <div className="relative min-h-screen border-2 border-red-500">
            {/* Sidebar (toggleable) */}
            <div className="flex border-2 border-green-500 ">
              <div className="w:1/4">
                <Sidebar />
              </div>
              <div className="w-full">
                <TopNav />
                {children}
              </div>
            </div>
          </div>
        </AppProvider>
      </body>
    </html>
  );
}
